#  Raspberry Pi RP2350 MicroROS tests (RP2040 backport) - The ROS Robot Project Research.
#  Copyright 2025 Samyar Sadat Akhavi
#  Written by Samyar Sadat Akhavi, 2025.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https: www.gnu.org/licenses/>.

name: Pico CodeQL Analysis

on:
    workflow_call:
        inputs:
            PICO_BUILD_SCRIPT_BRANCH:
                required: true
                type: string
            FIRMWARE_PATH:
                required: true
                type: string
            FREERTOS_KERNEL_IMPORT:
                required: true
                type: string

env:
    FIRMWARE_PATH: ${{inputs.FIRMWARE_PATH}}
    FREERTOS_KERNEL_IMPORT: ${{inputs.FREERTOS_KERNEL_IMPORT}}

jobs:
    analyze_pico:
        name: Analyze Pico source code
        runs-on: ubuntu-latest
        container: samyarsadat/service_images:pico-build-action-latest

        permissions:
            security-events: write
            contents: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Download MicroROS Library Artifacts
              uses: actions/download-artifact@v4
              with:
                  name: uros_library_artifacts
                  path: ${{env.FIRMWARE_PATH}}/libmicroros/firmware/build

            - name: Copy FreeRTOS Kernel Import File
              shell: bash
              run: |
                  cp "${FIRMWARE_PATH}/${FREERTOS_KERNEL_IMPORT}" \
                  "${FIRMWARE_PATH}/FreeRTOS_Kernel_import.cmake"

            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                  languages: c-cpp
                  build-mode: manual
                  queries: security-and-quality

            - name: Build Pico Source Code
              id: build
              shell: bash
              run: |
                  apt-get update && apt-get install -y wget
                  wget "https://raw.githubusercontent.com/samyarsadat/Pico-Build-Action/${{inputs.PICO_BUILD_SCRIPT_BRANCH}}/entrypoint.sh" -O pico-build.sh
                  chmod +x pico-build.sh
                  ./pico-build.sh "${FIRMWARE_PATH}" "build" "" "-DCMAKE_BUILD_TYPE=Release" "" "false" "Unix Makefiles"

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v3
              with:
                  category: "pico-source-code:c-cpp"